In [16]:
import numpy as np

sequence = []
chunk = np.array([0,1,2,3])
for i in range(50):
    sequence = np.append(sequence, chunk)

np.random.shuffle(sequence)
count = 0
for i in range(len(sequence)):
    while sequence[i] == sequence [i -1]:
        a = sequence[:i]
        b = sequence[i:]
        np.random.shuffle(b)
        sequence = np.append(a,b)  
print(sequence)

###this version tries to build whole sequencde from scratch
 def __findNextProbabilistic(self, current):  
        #max is updated as we search for the next state with the max number
        # of zero entries in its AM row
        maximum = 0
        next_candidate = []
        for j in range(self.num_states):
            # if the column is not the same state as current state
            if current != j:
                # if this transition is not exhausted
                if self.adj_matrix[current][j] > 0:
                    next_candidate.append(j)
        print(self.adj_matrix)
        print(self.sequence)
        print(next_candidate)
        np.random.shuffle(next_candidate)
        return int(next_candidate[0])

[ 0.  1.  3.  2.  0.  3.  1.  2.  3.  2.  3.  0.  3.  0.  1.  0.  1.  0.
  2.  0.  1.  0.  2.  3.  2.  0.  2.  0.  1.  3.  0.  3.  1.  2.  1.  2.
  1.  0.  1.  2.  0.  3.  2.  1.  3.  1.  0.  2.  3.  2.  3.  0.  3.  0.
  2.  3.  2.  3.  0.  3.  2.  1.  2.  0.  2.  3.  1.  3.  1.  3.  0.  1.
  0.  2.  0.  3.  0.  1.  0.  1.  3.  1.  2.  3.  1.  2.  1.  0.  2.  0.
  2.  1.  0.  1.  0.  2.  0.  1.  0.  2.  1.  3.  2.  3.  1.  0.  2.  0.
  3.  0.  1.  0.  1.  3.  1.  3.  0.  3.  1.  3.  1.  3.  1.  3.  0.  2.
  0.  2.  0.  3.  2.  1.  2.  0.  3.  2.  3.  2.  3.  2.  0.  3.  2.  1.
  2.  1.  3.  1.  2.  1.  2.  3.  2.  3.  2.  1.  2.  3.  0.  3.  0.  2.
  3.  0.  3.  1.  3.  0.  3.  1.  3.  1.  0.  3.  1.  0.  2.  1.  2.  1.
  3.  0.  3.  1.  2.  0.  2.  1.  2.  0.  1.  2.  1.  2.  0.  1.  3.  0.
  2.  1.]


In [24]:
import numpy as np
import random as rm

'''
To use this class:
1.) Create a seqGenerator object with optional argument int "num_states"
2.) Use makeBlockDeterministic or makeBlockProbabilistic
    to get a sequence of length equal to number of possible
    state transitions
'''

class sequence():
    def __init__(self, desired_length, num_states=4, probabilistic=True, initial=0):
        # desired length must (if you want something correct) be of 
        # form 12k + 1, where k is an int
        
        valid_transitions = (desired_length - 1)/12
        self.desired_length = desired_length
        self.sequence = []        
        self.num_states = num_states 
        
        # initialize the adj matrix. the ijth entry is the number of possible
        # transitions from i to j
        self.adj_matrix = valid_transitions*np.ones((self.num_states,self.num_states))
        for i in range(self.num_states):
            for j in range(self.num_states):
                if i == j:
                    self.adj_matrix[i][j] = 0
        
        if (probabilistic == True):
            self.makeBlockProbabilistic(initial)
        else:
            self.makeBlockDeterministic(initial)
   
    # this function finds the next state by attempting to greedily choose
    # in order to keep the number of transitions 'even'.
    def __findNextDeterministic(self, current):  
        #max is updated as we search for the next state with the max number
        # of zero entries in its AM row
        max = 0
        
        for j in range(self.num_states):
            # if the column is not the same state as current state
            if current != j:
                # if this transition has not already occured
                if self.adj_matrix[current][j] == 0:
                    # see how many null transitions the canditate next state has
                    count = np.sum(1-self.adj_matrix[j][:])
                    if  count > max:
                        max = count
                        next = j                 
                        
        assert type(next) == int, "next not found"
        return next

     # this function finds the next state by attempting to greedily choose
    # in order to keep the number of transitions 'even'.
    def __findNextProbabilistic(self, current):  
        #max is updated as we search for the next state with the max number
        # of zero entries in its AM row
        maximum = 0
        next_candidate = []
        for j in range(self.num_states):
            # if the column is not the same state as current state
            if current != j:
                # if this transition is not exhausted
                if self.adj_matrix[current][j] > 0:
                    next_candidate.append(j)
        print(self.adj_matrix)
        print(self.sequence)
        print(next_candidate)
        np.random.shuffle(next_candidate)
        return int(next_candidate[0])
        #dont forget to swap from increment to decrement when adj matrix is adjusted        
        '''
                if self.adj_matrix[current][j] == 0:
                    # see how many null transitions the candidate next state has
                    I want this to find the next state based on which candidate has the most transitions left
                    Can we choose a max sum of rows, then give it a window of plus or minus
                    
                    count = np.sum(1-self.adj_matrix[j][:])
                    if  count > maximum:
                        #reset the next_candidate list
                        next_candidate = []
                        next_candidate.append(j)
                        maximum = count
                        next = j
                    elif count == maximum:
                        next_candidate.append(j)
        
        # this randomly chooses an entry of the next_candidate array
        pick = rm.randint(0,len(next_candidate) - 1)
        next = next_candidate[pick]
        return int(next)
        '''
    
    
    def makeBlockDeterministic(self, state):
        self.sequence.append(state)
    
        # if not first element in sequence, mark the transition, 
        # and track sum of each row (transitions)
        if len(self.sequence) != 1:
            prev = self.sequence[len(self.sequence) - 2]    #this should be the value of prev state
            self.adj_matrix[prev][state] -= 1       #we increment to mark that this transition has occured
       
        next_state = self.__findNextDeterministic(state)
    
        # if we reached our desired length, append the next state and return
        if(len(self.sequence) == self.desired_length):
            prev = self.sequence[len(self.sequence) - 1]
            self.adj_matrix[prev][next_state] -= 1
            return self.sequence.append(next_state)
    
        #else keep building
        return self.makeBlockDeterministic(next_state)
    
    def makeBlockProbabilistic(self, state):
        self.sequence.append(state)
    
        # if not first element in sequence, mark the transition, 
        # and track sum of each row (transitions)
        if len(self.sequence) != 1:
            prev = self.sequence[len(self.sequence) - 2]    #this should be the value of prev state
            self.adj_matrix[prev][state] -= 1       #we increment to mark that this transition has occured
       
        next_state = self.__findNextProbabilistic(state)
    
        # if we reached our desired length, append the next state and return
        if(len(self.sequence) == self.desired_length):
            prev = self.sequence[len(self.sequence) - 1]
            self.adj_matrix[prev][next_state] -= 1
            return self.sequence.append(next_state)
    
        #else keep building
        return self.makeBlockProbabilistic(next_state)
 

    ####################################################################
    # Use these to print sequence, counts, transitions
    ####################################################################

    def getCounts(self):
        unique, counts = np.unique(self.sequence, return_counts=True)
        print(dict(zip(unique, counts)))
        
    def getSequence(self):
        print(self.sequence)
        
    def getTransitions(self):
        print(self.adj_matrix)
        

In [25]:
sequence = sequence(193)
sequence.getCounts()

[[  0.  16.  16.  16.]
 [ 16.   0.  16.  16.]
 [ 16.  16.   0.  16.]
 [ 16.  16.  16.   0.]]
[0]
[1, 2, 3]
[[  0.  16.  16.  15.]
 [ 16.   0.  16.  16.]
 [ 16.  16.   0.  16.]
 [ 16.  16.  16.   0.]]
[0, 3]
[0, 1, 2]
[[  0.  16.  16.  15.]
 [ 16.   0.  16.  16.]
 [ 16.  16.   0.  16.]
 [ 16.  16.  15.   0.]]
[0, 3, 2]
[0, 1, 3]
[[  0.  16.  16.  15.]
 [ 16.   0.  16.  16.]
 [ 15.  16.   0.  16.]
 [ 16.  16.  15.   0.]]
[0, 3, 2, 0]
[1, 2, 3]
[[  0.  16.  16.  14.]
 [ 16.   0.  16.  16.]
 [ 15.  16.   0.  16.]
 [ 16.  16.  15.   0.]]
[0, 3, 2, 0, 3]
[0, 1, 2]
[[  0.  16.  16.  14.]
 [ 16.   0.  16.  16.]
 [ 15.  16.   0.  16.]
 [ 16.  16.  14.   0.]]
[0, 3, 2, 0, 3, 2]
[0, 1, 3]
[[  0.  16.  16.  14.]
 [ 16.   0.  16.  16.]
 [ 15.  16.   0.  15.]
 [ 16.  16.  14.   0.]]
[0, 3, 2, 0, 3, 2, 3]
[0, 1, 2]
[[  0.  16.  16.  14.]
 [ 16.   0.  16.  16.]
 [ 15.  16.   0.  15.]
 [ 15.  16.  14.   0.]]
[0, 3, 2, 0, 3, 2, 3, 0]
[1, 2, 3]
[[  0.  16.  16.  13.]
 [ 16.   0.  16.  16.]
 [ 15.  16.   

IndexError: list index out of range